<!DOCTYPE html>
<html lang="nl">
<head>
	<meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

	<title>Eeterij H'eerlijk &bull; Wageningen</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="//use.typekit.net/app0omi.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>

    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="scripts/modernizr.2.8.3.min.js"></script>
</head>

<body data-spy="scroll" data-target="#nav">


<?php
// $seed = str_split('tqdsqqxhuusjwhwbynefmngziuerfpitijauvdyuqtemtdbsvaqowazefjyefsvwndjaiwinbdbgaoxpgkeclsltiittihlyiwuc acldopcjaskipulkoylnuxukjqsucatglzdqtaxgqcvtnbwgfsmvzxhpilpsdcflavclfvipubnvcpqidbmlabfdccpsmwsepjlb dpaiqyohdihjlnjcyvhllwqctndxpsdcdldkfpksdyzxrqfbvfxugpyvuffqlbmcdcfdueyqtnpbmpbevwjldxrdvcqzyioiagez fbptocmqsbkpfoveroxhtfvhmnfsgggmapqiemebbxacsqpzmfqiqtsraheawjpdifebgseboxbkzfsxpbfioqbiyovetnrhyqqz rpgfzakmedvagrzbfreuabtkocygtowndyehqpgammbvgeiptmmuilnqfuybpnvowpymrhsflmuufhqikrsovphlqbczievnmsyv sluqlbckfjrzmstkdobdbfhhibhgfnbveckejrkovoaiuydhvihrtcmdjianvfaiftjqkspudammwaoseohnqmmwtljgsdyswuxb huqsxtkaavlwlavaeapcludxbtkianyqsknhndyvzdnmvnxfkwauzpnrulqzxizpydpmxihjocemnzqmjrohzmfihhcjtvjjloqr dmzbnnjbalhaxhknwrkvxyxxgkzexcwziskgpukfkvpwaplbclqpbvvtorxgxsuotcjwmndpvxgxwibxzfoqiumnsbkcophkzuxx znmbcyhrmbsycxtknumtfhgkgabxcjamztkccvyvmiotdcaxinevfsgmnghynfqxpixwcesarzjgdzlpvjxhevipyhwymzdwnvqo kttpsygbcrmywgxbdzbcvgdtghgtlqzkxtlezsfgzqgsfqoeosegignhvcwfvtudkefdmeyjejtcfxaphgpkujpyjtyqlrboplgg srdxxivzgstmigduscavvyujkwtjzeylryhlfuwqbrypgsjzseadqizrbdzolosjvdtvpbizrscvamkxjbflrqhmyfpetmvgefmg qpjpdutanepmwtrtsczujomdfwqjjmubjvqtrgdxtrdnbpwomtvzeqiqmbculjunvgyprfgllhhdyiqlgvblhupegpoasumuyqzi slebnhddvsylpnvqscxddthikxotkectnnxsfhtmmwyoxnxxecdtyoubhccsfjzbqfclilezwpwtzxvxgfzqtufuazyowswpqlqr louayxpozkgjntrsbefoocmrlpjocbhoqulstiwvoqbshskkxnttyscksechcfpvdiskonknuojkwftoydzbuyozlerohiwmpudu hokzjycwblpjbydffkonsahrcjecvljycsnzsvvehfvamfhkakuvoejnfpfswvbxqtpsfwfwvwtzhtjfwlemfzfolbimloyrxtqy kkbrgprgjjkhnxjfpjetyxcdqpsaknckqudivdbvskyhrmxwkddgwtgzbvepqebrzuwyowhuncivgednunkghylouvcdqeonqbxd gviluhdkdoqiftgamraifgrfzmimrnyrrpryviowbjktvagcxdcqcanfzquhwzwgrqfdpgrzepwpjzvkoxrwevtzjqmkrgjkcqcw wfdgchxehynigqydbekomfduejumvytexaulikhnfpmwrrpnnqruissnuecfitltewhwobaeodriljdfhdgcedxornvmqkjkhplj ttixgadraplhsjrwcwhxjbjqmnmdvwqttrbtetlxaezzkwgqzlrsojqndmdsgdyoarsfwxurwraqvvqqztubodgmlebprdittrzy niufcvhnubtaloyenrmoulkqeuccwsgpsgxbymlvlxmdfgrcyijdouzlsulicinocrfpzbpgdbnaxeszlpgcgxjxtqxxqlqtlnvn cnctqvrkebrhvnjywignjlwsvxblawpowcxxzelevphsibopgertsesjjyhkgufusfiywurjbxisrqditrdtphejwaeruvoeujzr lxpubkqzzpcywguguqlaltgmotbvyxnvsxjjgsrnxhguqnszpchlfxyeaohdpqsdebmprbwbqxckmrctxgckfhmbpgpscjupykvg ryhrxhqirhlimkrdwsqmkmsmcpkpqkaaihnoivkyxnrdhkkutfawuqdhtvcfibtergnceergqiwkylbldggdsqmnscbutubosmzy gtgftsodylwglmisqvecfynxmnuenqodgdhhulzxuayrfgnydfxoukrrnjarqlabwpftexdpfbtctccmywovqtqwyzaaerlcdjhk alwztschxjspproeowdztpzdeuhblotrbfbprismckssgqkcpkfpilvpcfaagnirsflppcggpeqmqzmpudnxngpamvtbjhgqknmm qwkhelsbocqduaykgbsydnfdejssyqrrzexqeiizxbpyrgetlffvgxiluxwqxnwkweayulnzjhrgghyrwampsfqdhmkvcstsbenc nbafupxknampwkwslaclkenchmsvpgmnuvriqaojqfgdnijyicmbrfjktzrodtukmkfybexdznejuzreqsnagmrzoefuxukjfojz bqlzccluijqiavkumkjcxlewmaxyilskatxgjnabihtipbcleayeaslrmuywwiketkpvkgwkkxgivjbtbrokjanpsfkdcvljbxtw jgavedveqaygrpewmkraqyzmiwdekrmrsfqpjwrqppsxiltvrzjtgydvwrgjpwmtzpzzewiagqgsuffrzitlumwysgwxieadoolo nsjkytppkmkamvszjxokhwnisszmjdkiiyxdxpgfgqtrafvbnmxhwyhlloofqljqlulbrqcgxfhrzdqwpypvtxzrntyxzqfatnhj pyvdhamcbdzwliygvlddduqstqhwuufgaslfnczgcdvqincuujjvsfntmeoouihiflemedzrhudylbzikcxbaywebjkontrdccrv pgsqimrulbytdgrauwowbohwlwfqjheirykzkijypqaeumvqiwtuamniffziwxmfwvbyfjnqvnkfsdzurzrftcymbvyytdkcpzwy shsxbbnugmsoyseggsdhfzgpjsptrowhzvawlmkvgululgxbcblbzcsvczudmrhwervhkfzykauosgrcrkixxmfviwnuscibsgrw gyhrkmelmuhapwvjhszhmsaenbcevnfesikanyykncwhlvbeiiybbvthvylodnquybodyxktrziqkrshhrbptmiutaeqtoewnzhv stzigdckryclfwkjabnfpnvhypvptjcjwyqrqygozmjbttdbidxxbyscvwubeecooaiurcavkagbsgkobuzakcmprrevakrqmqzi dbvrnnflshanhvsdepvukodbxpuasxcixkkbovgpjmtvvmglydjvxzykfzjsrprilkflrtijcvoyghirhnhvwhslprrbiwjhnlwy aiydtdoatmzbephoiilfqdzxrgtlsbsflbrjqgirkutazsciqslehkxejiwmrsuutipqqotqutekrblvpdrdlkzepflguwjotvsk dkdxfouckyenbrcrkmjfnkdomdgtkqbfrvgjimtlygbpfyfkzgydmregwiadsslazndmogdowsxjsadefklebcyftygoeinchtzv sbvnggrutqqbydmoppndjrilwyhaohwfdwkafovoibclydmzbaeubqnpbxgoeadhmjflkyblhcuvphvoyulfbnumqcqseghqpmgf pduckvelhhjooefxlgyjmpeyrprulacqnoehuxpzxofnudrkupijacdgnynuvdxknjykpicfmwcinhsecrgboriqdfrlbiurvywz hgvfqiiomhwjigpzjqxbmsxtmtqnutqfiegpmffwgdfwgawrmscbwtimywsfavxzyyfkuuvsntbmoegujoyxxesiwpqgkxlasqhn dffafnmwpydjumxxlvrqzxieliozybvsyqaqawwtbxwvegychvaljotpqatsditueezkanlvxagdwcwaatcxquvqfsywvomivlin kxvcyfmyymqjpvnevkzliyzykcccgmbjdpwsocrcugmuvxnhetpijkultxqdvhkgmklkxgafuyumcemeuifktqgrkccxwxtqwegi ezgucptlmjweaghvdzmdebxuzcdldlvwbmcrvibpaonntgxohefrsacxuzwjerbhmynbpbocuzphgyxnbpzeuealhixqbykffdtv pdeglkyehajbmariqqbdupanzijtpjczotplltbdlmdnggdllfcjkhvjyrvumoaeetxuitcabhdnohymzkahbzxwcgxnnfovxgte ofbfpmpxkjavmbhyooaivtboznbsxuhsflkkjjtdafeyvnmfyhdhrxirrdjggwlgxjndneunafznijotqqznfrhoegbekeghdkvr rrsjhcmvrsopafpikzyxuuffiunizsprqecbfarixkcydnkrksssvyixefotwcbuylppzdtujachdasnaoavcgwjudcxrkquwzth wapxwtcgkixtngfzsqdmrfuwodrurqdmssfeojolnsyxpgvkokjzruterunacdvubxhqrkkurdzrfcappzeyiknlcdbywkpzvpxy tvbkejqchtimsvqvxdcryvroalfpoceynvachrzevihegtrsmzfcukzmwerdyudomsuiawxvyzdqzvelgxsoaavlkmzljuqahkea uwxayohbilgtcevqgctczbgyhgigifnvupdaawoxiuimxknylzdapsjwmbktalumqecsstummkikrogwfuyvfeduakhhnwxfrcdd xculvvupmbgkkotapimykqhkjgmqkbtbxlfojkzsfpmfttxummdfqabnbgdszdedqizveciiikqgwglejgjswcjzfjkrsjuffgxv allxdrheawlklysjcjrxmgelwrbhnvvzyhrysmdkwvytruinlywicpqmpyhffczkyuexszpygjtxflcryrelpgycljayevrdsrsp ziofoqwcwbxohqrdtqxxszvgewjdlevswcilnwmkbiwktchmlxbamwgcbuxehizjjykxusgcugmtxjehmawdolcvxewhzoobxgqj qwbtgtjukhcbiphtvxcuufagokkiwyivlpkvuwluftmlnmzwrsxabnttnzdkwnmuaiojkuvaqrynnkrncvxmqrmlskqippxxyhdi dmjosdgzwdmoyjseyqleldmjdqgakvksipobqvgxdmeqxjilcxytmsziaugbhmpxvtnimxpokvgacttvrbrjiegmwtlyuettgojt rtmavfrujkxjhpymxbajrmvdcweantmiqclhkjsecntgpgfzyhcvahtifiusqbzugqbgogsdnwafbfrumpfntmwvtxybdejewpxm pzcwnwqywccthldyhvdjfwybdsqogdcerjdyylpuodivpsybggbcwscoivxiobqrymwdkkfdldqpevutuuiexbzvmkoictubigst gbjbuqdqttamxlhcyxiyqynxuegkiekgegtnvgpfjkjfklnpykuaumnoomtxifyhoauilrowiwbmziekrftxuzrzckukxrvvonhq mfiyjczdnizazxrbuntygaqdvuxodttonphvamrkzpdxamhvkhfzreckhxakhixqkbdmxlfifmenzwxzjlwmnrizkhirhbklunui ovwkgzgxldhrjnlovilivkmfbypneujlitnxoqpwqppargjswisfrzfamvricmocangeriludzckwtoferimzcbbzpzhkwodtixw numrwhwdawmknfzybvhujketjvlwznilnztwccswdqvxcwlvcgnqzxlwjpiamvloydjommrpsiythwgabbbhsxwwbyjyxyjdyiyf vjsulzhpwfirhrfehssbfykqnhmzedsdvjhzkkdfgqscjhjtdopxttquzrhofjbxmwqbdauqupxhyfztmjwtdunglpoeadsqpcpt psknjqbkbgzprlackzyttwywjqgdjjbdyrczllosnndmcvtmbrhmyyrcfdodazercblwxbirutpfepvqeukgvqpmqfjbpcconxhn vjgbbjlitoebezthvhqgnagdjgbtgnroaudggnydrrhfxonivxndgfswlafbyaqayweuilpybaevjultrlhmrcczlhmyoejztqje eaudfcratfdurdlpxayseothufhtbwdedkektaymigtdoczprrzjzeeszbveuhyjfndjlvxmgwiyvzfpgxzrmpmhroxdutlhsfnh sdrehzxkhcghzjexqgbzwecrzaznkwpvccjlnylwnzrsyjzxmbgqlaeqbnvepggadenxilhjzeyqopskiqrrkmkxtjyhqphugkpc oszzdbdelwlijcyjwbkzhasqwymrchtelzzmyeccsewghhmghwcprsudsfahcqyxclwndliknfcccakajadojiqxpnsaffcqwlct ugudrethqcesofeviabadxjuzgsapmpjfzruhwbgocuhftqihujhjiermdqhzxcshgielcuytowuqleujgdbwomzwlwmzmuvjahs tohdmqtojuhgtawhrtxagmrxggxumqflrtebkimxgpscvookchhupjvufkzeuxrhempwebwszvbokbpoxfhgmupadxlnjevgwsvt gphzihguzrvtkocivxqrlxsxcantshwrwjhtnmfrjkgnpsgpauzycvgtxwncywhoxdjpjtpzrsuoesjimjevlfzisssgczuyphoj ygilabogljjosrxwhfqsgkttxznonrhphmiwwrrcwstnphzrtrstkkqnvujrvqgtnnlcrwujchiwrdceogqdcbwmvgdovguldjyf aegqebpcqxuuuzovnmefkvxhszzqodkysagnibttblkeabuxuovfytnwutvjzvnwsdqcajimadlpbikgrzgwztxqfldscxczlyfz othyrzxhshvsekjhrbqpduummaafgluhaceczmxzptngnqxgwgohfdmeyhrgmlnucwsioxxzwxmgidmrbzoknmstknwkvttzeizx gwtqcaessgzuuxilepyphasuoowmsnvvkuylcjfwccrdscsfmakiinvtcpldpbckciekjtvxvjtzwuulsuftmknktyxkfpubaxei tqffjnonfttojzfcufcrmhoqrnaccotsmaybrykoskvxwktonzqcgsnrqegsercknntgznqjmilyzswghritijekmwoadjeeksdx kfdqpsvrshizzryviiwomuveuvaslckwgmsyboqbnbvcqkuxseojgegwuuxqebhivrcoteysddqzczzeibwnamhsamgebsvedrff fqmuhziezpjrzfzmdixdnfkokagxlbjfaqksigwvwxsuvmmecevapmeqvtecxxlmkfeyherldmpdqeenftgrqldmvthqbuqezgpl jnrodgrphzpapxgsslciwoeedxyvbdunzbtfzitbadvsrxeybxkmdpfikdhqxspcemjpaedosevsmiahtragewssjdmekfjqkboz fxyagxkfeivnebqsxbbighwgztrjbwzwdmdcqwmuwehnydiradixfsgedxjsxarknbmtkbzleulogqzkxmyuxbfajnzvnctrgomr ofkagnqtsqbicvmwtcfqnmdkuxnbrakeehehqnkyzquyujpqtqgzdaplwyvptnbhyynliugctciotubofmzaghhughisxudmkpae bwcmcwumewvvgfcqmhljprrhnidkntrdlkwcncyslarokgiwqwrljfufbmbquclregbwbfjqaxxgcvltnopnayjztgqqrrogmssq slpsgpszcsmcqsvuximrahdybuudybfkvrrsktqlchxwcwsamntlohwalbypnimgmsvlhbqgdzstbzmvsynicxwkqtcchpirpunj eacfsbqigmleptoziibhekawazqwgdhsflcyecjyrfvpumgqtcwqqzuzalrrwppxzjkeeaihulqdvyydxqfecyoqlywjndywrjiv fliumyscldmvaqefpmasrvptyopnuictpuhqjjatuzfyvkqaxrzzvwjuxqudsetiyhohkcfltnjixxgdqceehovsjztgxfnlgpzq rcrlnrbdbvypirtmjtzmdwpeuyldtjzukbuyvqbifhuorinrmvvevkluhkkqfzrtuzuolgpmhvntvzmeoiuaaikwrxqpofxivbci txrupiqeesdxnndhcswkedwprdjsmrpxiiekyjlnloqgyfxngbrtdauanywgaujzijbrsjcbuoivvsxtflktazktrxcxpfhlrxly tgzgjavpxnkhgqshqykgruaojrxijptshtwvibwqkfmcnmuyqajrpjrvktjodqnbuautsnuwfbzmtcvlawxayeexavyqpwynmwqo hosgtdmvfqumkgjrebobforomfzmoxfeoulwnemmasqgktgkxgulxvcjjatwcdcpijqazebucmchieokppgsbyvditvflxjgjact gqeieniojtudrbyxmyfzfzuhxupjjzdaqnqrkkuzgnnklalyrmirpjegdnjtepgqbyeelqfmnlaxplpwqrtijlbwjsqngqlypnzf pestulycagqjonziqharpbybosvnlyruwifmeygtduliyvixwyolbrwrlqnlidhtsukecmsgowdrdqejfwyibvzywwkuttaxbbxp npgblukjcfkznkltxunmogzcftlvkbnydmczjahydzmqtkztdqkchzfwtqcjtcximoyyjnyhbxralzgsrfqxijesmakzxlauaedo ammoevkidqlxeutnsrepvvbxneazlzmmasiqyzllotjzgoaghejsuvexpgribebuakixbxmxqwyoppfxufgtagletgvciyujxrtp vuscwjnsxbbmusuokpiupmjmxzszhxzesfgqlqnrlpzdptouzatljmylrbctsyedvvekadaohyvwxbngzfrgccmazyzabxfnbofu stllzunsutcgjcauflummugxctjbidxowafkthdoztzldwgugzbpuvmzmbgswqlsstupcooqtavnlwrrbdvzlhsmrbrvvpdofwvp ptktnjsqcavrghvqsbosetehvaalohzkqhupeegjyjoqqlxdyhjunwzxeqprjlgauptoboxcmwkvfnzeiooggejhvlgplwghavva zcjthoxyderewsllsersafuksqykzrmxsurditcccmwlrjpgkrrmlnufkxsqyodyzgzpjxrymgqvbtlslmcgvlxgyjlczqdtsewa lqkzmvxbnjxuxplytxfzkqxkywneebclnyltfnykdjteiswtojxkcrdijxbfiipthtdbceqjgeungxmzyjsrejoysgmvdczjdwip ywwjlxzjwxxhrbftbfrslabsslapermbsadwkmtuejrnlcgocoameggkvfkruezevpnvkujdnwpbcrkondtmsjonoitllsvboyrt jlhubijmggbtgjbmqinpjwwvabyzjnogluxmgohfhrvdoeijwbveilhlxajmztqwgwfsqtrhltxnpvedygylnjfpirdxdopojeoy gclbxpyhactydatrrnauzqeuwliwjynpyumzmjlqihfjqxxzhluryeiyaqyjrbmwnueqllztykhsxevxfzvigdqizpkvunciwvsa'); // and any other characters

// $rand = rand(2, 10);
// foreach ($seed as $index => $key) {
//   if ($index % $rand == 0) {
//     echo ' ';
//     $rand = rand(2, 10);
//   }
//   echo $key;
// }
// exit();
?>

<nav class="navbar navbar-default navbar-fixed-top fade-in-content" id="nav">
    <div class="container">
      <div class="row">
         <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse">
              <ul class="nav navbar-nav">
                <li><a href="#about">Over ons</a></li>
                <li><a href="#menu">De kaart</a></li>
                <li><a href="#reserve">Reserveren</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#organic">Onze visie</a></li>
              </ul>
            </div>
        </div>
    </div>
  </div>
</nav>

<?php include_once('templates/about.php'); ?>

<?php include_once('templates/menu.php'); ?>

<div class="photo photo-2"></div>

 <?php include_once('templates/reserve.php'); ?>

<?php include_once('templates/contact.php'); ?>

<div class="photo photo-3"></div>

<?php include_once('templates/organic.php'); ?>

<div class="footer-bar"></div>


<script src="scripts/jquery-2.1.3.min.js"></script>
<script src="scripts/bootstrap.min.js"></script>
<script src="scripts/map.js"></script>

<script>
    $('.navbar a').click(function(){
    $('html, body').animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
    }, 1000);
    return false;
});
</script>

</body>
</html>